### ISSUE TITLE
It do't support the chinese coding

### ISSUE THREAD

**Issue by jiahut** [njvack/bids-json-writer#6] opened 2018-08-14 12:24 UTC
For example

> cat  test.md
```md
# issues

## 紧急bug

```

>  md_to_json test.md 

```json
{
  "issues": {
    "\u7d27\u6025bug": ""
  }
}
```

hope it should be:

``` json
{
  "issues": {
    "紧急bug": ""
  }
}

```

**Comment by njvack** [comment] 2018-09-13 19:43
Wow, I left this for a long time. This is almost certainly a duplicate of #1, assuming your data is in UTF-8 to begin with.

I don't currently have time to fix this; however there's a proposed fix in that issue and I'll give it a try sometime soon.

**Closed as completed** 2023-05-31 23:11 UTC
